# Generated by Django 3.2.20 on 2023-08-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='category',
        ),
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_ideas', to='categories.Category', verbose_name='Category'),
        ),
    ]
