# Generated by Django 3.2.20 on 2023-08-05 05:57

from django.db import migrations

def copy_categories(apps, schema_editor):
    Idea = apps.get_model("ideas", "Idea")
    for idea in Idea.objects.all():
        if idea.category:
           idea.categories.add(idea.category)


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20230805_0556'),
    ]

    operations = [
        migrations.RunPython(copy_categories),
    ]
